# minimal unit test environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  ### environment-test-webdriver.yml ###
  - selenium >=4.19.0,<4.20
  ### environment-test-webdriver.yml ###

  ### environment-test.yml ###
  # build
  - pip
  - doit
  - python-build
  - flit-core >=3.9,<4
  # run
  - jupyterlite-pyodide-kernel >=0.3.1,<0.4.0
  - jupyterlite-core >=0.3.0,<0.4.0
  - pyodide-lock-with-wheel >=0.1.0a4,<0.1.0a6
  - tornado
  # extra
  - python-libarchive-c
  # test
  - pytest >=8,<9
  - pytest-cov
  - pytest-html
  ### environment-test.yml ###
