"$schema" = "http://json-schema.org/draft-07/schema#"

title = "Pixi project"
description = "This form builds a predictable `pixi` environment."
type = "object"

[properties.name]
type = "string"
default = "my-jupyterlite-site"
