"$schema" = "https://urljsf.rtfd.org/en/latest/_static/urljsf/schema/v0/form.schema.json"

[forms.build]
schema = "./build.schema.toml"

[forms.project]
schema = "./project.schema.toml"

[templates]
url = """
{% import "_pixi_toml" as pt %}
{% import "_jlc_json" as jl %}

{{
  {
    "pixi.toml": pt.pixi_toml(data) | trim,
    "lite": {
      "jupyter_lite_config.json": jl.jlc_json(data) | trim
    }
  } | to_zip_url
}}
"""
submit_button = "Download Project Archive"
download_filename = "{{ data.project.name }}.zip"

below_build = """
{% import "_jlc_json" as jl %}
Your `jupyter_lite_config.json`:

```
{{ jl.jlc_json(data) | trim }}
```

"""

below_project = """
{% import "_pixi_toml" as pt %}
Your `pixi.toml`:

```
{{ pt.pixi_toml(data) | trim }}
```
"""

_pixi_toml = '''
{% macro pixi_toml(d) %}

{{
  {
    "project": {
      "name": d.project.name
    },
    "dependencies": {
      "jupyterlite-pyodide-lock-with-recommended": "0.1.0a0"
    },
    "tasks": {
      "build": {
        "cmd": "cd lite && jupyter lite archive"
      },
      "serve": {
        "cmd": "cd lite/_output && python -m http.server -b 127.0.0.1",
        "depends-on": ["build"]
      }
    }
  }
  | to_toml
  | replace(r/(\[.*?\]\n)+(\[.*?\]\n)/gm, "$2")
  | replace(r/\n\n(\n+)/g, "\n\n")
  | trim
}}

{% endmacro %}
'''

_jlc_json = '''
{% macro jlc_json(d) %}

{{
  {
    "PyodideLockAddon": {
      "enabled": true,
      "locker": "BrowserLocker",
      "specs": d.pyodide.specs
    }
  }
  | to_json
}}

{% endmacro %}
'''

[nunjucks]
filters = ["toml", "json", "zip", "yaml"]
