default: true

line-length:
  line_length: 88
  code_blocks: false
  tables: false

# specific rules ###############################################################
MD033:
  allowed_elements:
    - a
    - b
    - br
    - button
    - code
    - details
    - div
    - form
    - i
    - iframe
    - input
    - kbd
    - li
    - pre
    - section
    - summary
    - ul

MD041: false
