version: 2

build:
  # ubuntu-24.04 does not have `libasound2` (and likely others)
  os: ubuntu-22.04
  # needed for `firefox`: precludes use of `commands` below
  # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages
  apt_packages:
    - libasound2
    - libatk1.0-0
    - libcups2
    - libdbus-glib-1-2
    - libgtk-3-0
    - libnss3
    - libpangocairo-1.0-0
    - libx11-xcb1
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxi6
    - libxrandr2
    - libxss1
    - libxtst6
  tools:
    # `mambaforge-latest` will now start failing: we just need a working `mamba`
    python: mambaforge-23.11
  # cannot be `commands` due to `apt_packages`, as above
  jobs:
    pre_build:
      - pixi install --environment=build
      - pixi install --environment=docs
      - pixi run build
      - pixi run docs-lite
      - pixi run docs-sphinx

sphinx:
  builder: html
  configuration: docs/conf.py

conda:
  environment: docs/environment.yml
