version: 2

build:
  # ubuntu-24.04 does not have `libasound2` (and likely others)
  os: ubuntu-22.04
  tools:
    # `mambaforge-latest` will now start failing: we just need a working `mamba`
    python: mambaforge-23.11
  jobs:
    pre_build:
      - pixi install --environment=build
      - pixi install --environment=docs
      - pixi run build
      - pixi run docs-pip
      - pixi run docs-lite
      - pixi run docs-sphinx

sphinx:
  builder: html
  configuration: docs/conf.py

conda:
  environment: docs/environment.yml
